backend/controllers/CategoryController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Category;
use common\models\CategorySearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CategoryController implements the CRUD actions for Category model.
 */
class CategoryController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update' , 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Category models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CategorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Category model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Category model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Category();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Category model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Category model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Category model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Category the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Category::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/ItemController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Item;
use common\models\ItemSearch;
use common\models\Image;
use yii\filters\AccessControl;
use yii\helpers\FileHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * ItemController implements the CRUD actions for Item model.
 */
class ItemController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update' , 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Item models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ItemSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Item model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Item model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Item(['scenario' => 'create']);

        if ($model->load(Yii::$app->request->post())) {
            $model->image = UploadedFile::getInstance($model, 'image');
            $model->file = UploadedFile::getInstance($model, 'file');
            $model->images = UploadedFile::getInstances($model, 'images');
            $filename = $model->file->name;
            $model->filename = $filename;

            if ($model->validate() && $model->save()) {
                $dir = Yii::getAlias('@frontend/web/uploads/item/' . $model->id . '/');
                FileHelper::createDirectory($dir);

                // Save main image
                $model->image->saveAs($dir . 'main.jpg');

                // Save file
                $model->file->saveAs($dir . $filename);

                // Save images
                if ($model->images) {
                    foreach ($model->images as $image) {
                        $imageModel = new Image();
                        $imageModel->item_id = $model->id;
                        $imageModel->save();

                        $image->saveAs($dir . $imageModel->id . '.jpg');
                    }
                }
            }

            return $this->redirect(['view', 'id' => $model->id]);
        }

        $model->date = date('Y-m-d H:i');
        $model->likes = 0;
        $model->dislikes = 0;
        $model->downloads = 0;
        $model->author = Yii::$app->user->identity->username;

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Item model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $model->image = UploadedFile::getInstance($model, 'image');
            $model->file = UploadedFile::getInstance($model, 'file');
            $model->images = UploadedFile::getInstances($model, 'images');

            if ($model->validate() && $model->save()) {
                $dir = Yii::getAlias('@frontend/web/uploads/item/' . $model->id . '/');

                // Save main image
                if ($model->image) {
                    $model->image->saveAs($dir . 'main.jpg');
                }

                // Save file
                if ($model->file) {
                    $filename = $model->file->name;
                    $model->filename = $filename;
                    $model->save();
                    $model->file->saveAs($dir . $filename);
                }

                // Save images
                if ($model->images) {
                    $imageModels = Image::findAll(['item_id' => $model->id]);
                    if ($imageModels) {
                        foreach ($imageModels as $image) {
                            $file = $dir . $image->id . '.jpg';

                            if (file_exists($file)) {
                                unlink($file);
                            }

                            $image->delete();
                        }
                    }

                    foreach ($model->images as $image) {
                        $imageModel = new Image();
                        $imageModel->item_id = $model->id;
                        $imageModel->save();

                        $image->saveAs($dir . $imageModel->id . '.jpg');
                    }
                }
            }

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Item model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);

        $dir = Yii::getAlias('@frontend/web/uploads/item/' . $model->id);
        FileHelper::removeDirectory($dir);

        Image::deleteAll(['item_id' => $model->id]);
        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Item model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Item the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Item::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/FileController.php
<?php

namespace frontend\controllers;

use common\components\Counter;
use common\models\Category;
use common\models\Item;
use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\Cookie;
use yii\web\NotFoundHttpException;

class FileController extends Controller
{
    public function actionCategory($category)
    {
        $model = $this->findCategory($category);

        $ids = [$model->id];

        foreach (Category::findAll(['parent_id' => $model->id]) as $category) {
            $ids[] = $category->id;
        }

        $query = Item::find()->where([
            'category_id' => $ids
        ]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'sort' => [
                // Order by date for default
                'defaultOrder' => [
                    'date' => SORT_DESC,
                ]
            ],
            'pagination' => [
                // Prevent creating additional params in the URL. For SEO
                'forcePageParam' => false,
                'pageSizeParam' => false,
            ],
        ]);

        return $this->render('category', [
            'model' => $model,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($item)
    {
        $model = $this->findModel($item);

        Yii::$app->counter->plus($model);

        return $this->render('item', [
            'model' => $model,
        ]);
    }

    public function actionDownload($item)
    {
        $model = $this->findModel($item);

        $model->downloads++;
        $model->save();

        $file = Yii::getAlias('@frontend/web/uploads/item/' . $model->id . '/' . $model->filename);

        return Yii::$app->response->sendFile($file, $model->filename);
    }

    public function actionRate($item, $up)
    {
        $model = $this->findModel($item);

        $name = md5($model->name . 'views');

        $session = Yii::$app->session;
        $cookies = Yii::$app->request->cookies;

        if (!$session->has($name) and $cookies->has($name)) {
            $session->set($name, $model->id);
        }

        if (!$cookies->has($name) and $session->has($name)) {
            Yii::$app->response->cookies->add(new Cookie([
                'name' => $name,
                'value' => $model->id,
                'expire' => time() + 31556926,
            ]));
        }

        if ($session->has($name) and $cookies->has($name)) {
            $session->setFlash('danger', 'Ваш голос уже был учтен ранее.');
        } else {
            if ($up === '1') {
                $model->likes++;
            } elseif ($up === '2') {
                $model->dislikes++;
            }

            $session->set($name, $model->id);

            Yii::$app->response->cookies->add(new Cookie([
                'name' => $name,
                'value' => $model->id,
                'expire' => time() + 31556926,
            ]));

            $model->save();

            $session->setFlash('success', 'Ваш голос был засчитан');
        }

        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * Finds the Item model based on its slug.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $slug
     * @return Item the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($slug)
    {
        if (($model = Item::findOne(['slug' => $slug])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('Файл не найден');
        }
    }

    /**
     * Finds the Category model based on its slug.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $slug
     * @return Category the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findCategory($slug)
    {
        if (($model = Category::findOne(['slug' => $slug])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('Категория не найдена');
        }
    }

}

backend/views/item/_form.php
<?php

use common\models\Category;
use common\models\Image;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use vova07\imperavi\Widget as Imperavi;
use kartik\widgets\DateTimePicker;
use kartik\widgets\FileInput;

/* @var $this yii\web\View */
/* @var $model common\models\Item */
/* @var $form yii\widgets\ActiveForm */

// Get category list
$category_models = Category::find()->all();
$categories = ArrayHelper::map($category_models, 'id', 'name');

// Get main image
$image = $model->isNewRecord ? false : Html::img(
    $model->imageUrlBackEnd,
    ['class' => 'file-preview-image']
);

// Get file images
$imagesModel = Image::find()->where(['item_id' => $model->id])->all();
if ($imagesModel) {
    $images = [];

    foreach ($imagesModel as $imageModel) {
        /** @var $imageModel common\models\Image */
        $images[] = Html::img(
            Yii::$app->urlManagerFrontEnd->baseUrl . '/uploads/item/' . $model->id . '/' . $imageModel->id . '.jpg',
            ['class' => 'file-preview-image']
        );
    };
} else {
    $images = false;
}

// Get uploaded file
$file = $model->isNewRecord ? false : "<div class='file-preview-text'>"
    . "<h2><i class='glyphicon glyphicon-file'></i></h2>"
    . $model->filename
    . "</div>";
?>

<div class="item-form">

    <?php $form = ActiveForm::begin([
        'options' => [
            'enctype' => 'multipart/form-data'
        ],
    ]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'image')->widget(FileInput::className(), [
        'options' => [
            'accept' => 'image/*',
        ],
        'pluginOptions' => [
            'showUpload' => false,
            'browseLabel' => 'Выбрать',
            'removeLabel' => 'Удалить',
            'removeClass' => 'btn btn-danger',
            'initialPreview' => $image,
        ],
    ]) ?>

    <?= $form->field($model, 'images[]')->widget(FileInput::className(), [
        'options' => [
            'accept' => 'image/*',
            'multiple' => true,
        ],
        'pluginOptions' => [
            'maxFileCount' => 10,
            'showUpload' => false,
            'browseLabel' => 'Выбрать',
            'removeLabel' => 'Очистить',
            'removeClass' => 'btn btn-danger',
            'initialPreview' => $images,
        ],
    ]) ?>

    <?= $form->field($model, 'file')->widget(FileInput::className(), [
        'pluginOptions' => [
            'showUpload' => false,
            'browseLabel' => 'Выбрать',
            'removeLabel' => 'Очистить',
            'removeClass' => 'btn btn-danger',
            'showPreview' => false,
            'initialPreview' => $file,
        ],
    ]) ?>

    <?= $form->field($model, 'video')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'short')->widget(Imperavi::className(), [
        'settings' => [
            'minHeight' => 100,
        ],
    ]) ?>

    <?= $form->field($model, 'description')->widget(Imperavi::className(), [
        'settings' => [
            'minHeight' => 200,
        ],
    ]) ?>

    <?= $form->field($model, 'category_id')->dropDownList($categories, [
        'prompt' => '--- выберите категорию ---',
    ]) ?>

    <?= $form->field($model, 'date')->widget(DateTimePicker::className(), [
        'pluginOptions' => [
            'autoclose' => true,
            'todayHighlight' => true,
            'format' => 'yyyy-mm-dd hh:ii',
            'todayBtn' => true,
            'convertFormat' => true,
        ],
    ]) ?>

    <?= $form->field($model, 'author')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'slug')
        ->textInput(['maxlength' => 255])
        ->hint('Если пусто - будет сгенерировано с имени') ?>

    <?= $form->field($model, 'meta_description')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'meta_keywords')->textInput(['maxlength' => 255]) ?>

    <div class="form-group">
        <?= Html::submitButton(
            $model->isNewRecord ? 'Добавить' : 'Сохранить',
            ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']
        ) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/item/_search.php
<?php

use common\models\Category;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\ItemSearch */
/* @var $form yii\widgets\ActiveForm */

$category_models = Category::find()->all();
$categories = ArrayHelper::map($category_models, 'id', 'name');
?>
<div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
        <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                Поиск файлов
            </a>
        </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
        <div class="panel-body">
            <div class="item-search">

                <?php $form = ActiveForm::begin([
                    'action' => ['index'],
                    'method' => 'get',
                ]); ?>

                <?= $form->field($model, 'name') ?>

                <?= $form->field($model, 'category_id')->dropDownList($categories, [
                    'prompt' => '--- выберите категорию ---',
                ]) ?>

                <?= $form->field($model, 'id') ?>

                <?= $form->field($model, 'author') ?>

                <?= $form->field($model, 'slug') ?>

                <div class="form-group">
                    <?= Html::submitButton('Поиск', ['class' => 'btn btn-primary']) ?>
                    <?= Html::resetButton('Очистить', ['class' => 'btn btn-default']) ?>
                </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>
    </div>
</div>

backend/views/item/create.php
<?php
/* @var $this yii\web\View */
/* @var $model common\models\Item */

$this->title = 'Добавить Файл';
$this->params['breadcrumbs'][] = ['label' => 'Файлы', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="item-create">

    <h1 class="page-header"><?= $this->title ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/item/index.php
<?php
use kartik\icons\Icon;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\ItemSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Файлы';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="item-index">

    <h1 class="page-header">
        <?= $this->title ?>
        <?= Html::a(Icon::show('plus'), ['create'], ['class' => 'btn btn-success pull-right']) ?>
    </h1>

    <?= $this->render('_search', [
        'model' => $searchModel
    ]) ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'summaryOptions' => ['class' => 'alert alert-info'],
        'columns' => [
            [
                'attribute' => 'image',
                'format' => 'html',
                'value' => function ($model) {
                    /** @var $model common\models\Item */
                    return Html::img($model->imageUrlBackEnd, ['width' => 100]);
                },
            ],
            'name',
            [
                'attribute' => 'category_id',
                'format' => 'html',
                'value' => function ($model) {
                    /** @var $model common\models\Item */
                    return Html::a($model->category->name, ['category/view', 'id' => $model->category->id]);
                },
            ],
            'date',
            'slug',
            // 'downloads',
            // 'likes',
            // 'dislikes',
            // 'author',
            // 'description:ntext',
            // 'meta_description',
            // 'meta_keywords',

            ['class' => 'common\components\ActionButtonGroupColumn'],
        ],
    ]); ?>

</div>

backend/views/item/update.php
<?php
/* @var $this yii\web\View */
/* @var $model common\models\Item */

$this->title = 'Редактировать файл: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Файлы', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактировать';
?>
<div class="item-update">

    <h1 class="page-header"><?= $this->title ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/item/view.php
<?php
use common\models\Image;
use kartik\icons\Icon;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Item */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Файлы', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

// Get file images
$imagesModel = Image::find()->where(['item_id' => $model->id])->all();
if ($imagesModel) {
    $images = null;

    foreach ($imagesModel as $imageModel) {
        /** @var $imageModel common\models\Image */
        $images .= Html::img(
            Yii::$app->urlManagerFrontEnd->baseUrl . '/uploads/item/' . $model->id . '/' . $imageModel->id . '.jpg',
            [
                'width' => '200px',
                'class' => 'img-thumbnail'
            ]
        );
    };
} else {
    $images = false;
}
?>
<div class="item-view">

    <h1 class="page-header">
        <?= $this->title ?>
        <div class="btn-group pull-right">
            <?= Html::a(
                Icon::show('eye'),
                Yii::$app->urlManagerFrontEnd->createUrl(['file/view', 'item' => $model->slug, 'category' => $model->category->slug]),
                [
                    'class' => 'btn btn-success',
                    'target' => '_blank',
                    'title' => 'На сайте',
                ]
            ) ?>
            <?= Html::a(
                Icon::show('pencil'),
                ['update', 'id' => $model->id],
                [
                    'class' => 'btn btn-primary',
                    'title' => 'Редактировать',
                ]
            ) ?>
            <?= Html::a(
                Icon::show('trash'),
                ['delete', 'id' => $model->id],
                [
                    'class' => 'btn btn-danger',
                    'title' => 'Удалить',
                    'data' => [
                        'confirm' => 'Вы действительно хотите удалить этот файл?',
                        'method' => 'post',
                    ]
                ]
            ) ?>
        </div>
    </h1>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            [
                'attribute' => 'image',
                'format' => 'raw',
                'value' => Html::img($model->imageUrlBackend, [
                    'class' => 'img-thumbnail',
                    'width' => 200,
                ]),
            ],
            [
                'attribute' => 'images',
                'format' => 'html',
                'value' => $images,
            ],
            [
                'attribute' => 'file',
                'format' => 'html',
                'value' => Html::a(
                    $model->filename,
                    Yii::$app->urlManagerFrontEnd->createUrl(['file/download', 'item' => $model->slug])
                ),
            ],
            [
                'attribute' => 'category_id',
                'format' => 'html',
                'value' => Html::a($model->category->name, ['category/view', 'id' => $model->category->id]),
            ],
            'downloads',
            'likes',
            'dislikes',
            'date',
            'author',
            'slug',
            'name',
            'short:html',
            'description:html',
            'meta_description',
            'meta_keywords',
        ],
    ]) ?>

</div>