common/models/Category.php
<?php

namespace common\models;

use Yii;
use yii\db\ActiveRecord;
use Zelenin\yii\behaviors\Slug;

/**
 * This is the model class for table "category".
 *
 * @property integer $id
 * @property integer $parent_id
 * @property string $slug
 * @property string $name
 * @property string $meta_description
 * @property string $meta_keywords
 *
 * @property Category $parent
 * @property Category[] $categories
 * @property Item[] $items
 */
class Category extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['parent_id'], 'integer'],
            [['slug', 'name', 'meta_description', 'meta_keywords'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'parent_id' => 'Родительская',
            'slug' => 'URL',
            'name' => 'Название',
            'meta_description' => 'Meta Описание',
            'meta_keywords' => 'Meta Ключевые слова',
        ];
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'slug' => [
                'class' => Slug::className(),
                'attribute' => ['name'],
            ],
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getParent()
    {
        return $this->hasOne(Category::className(), ['id' => 'parent_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategories()
    {
        return $this->hasMany(Category::className(), ['parent_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItems()
    {
        return $this->hasMany(Item::className(), ['category_id' => 'id']);
    }
}

backend/controllers/CategoryController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Category;
use common\models\CategorySearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CategoryController implements the CRUD actions for Category model.
 */
class CategoryController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update' , 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Category models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CategorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Category model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Category model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Category();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Category model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Category model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Category model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Category the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Category::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/FileController.php
<?php

namespace frontend\controllers;

use common\components\Counter;
use common\models\Category;
use common\models\Item;
use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\Cookie;
use yii\web\NotFoundHttpException;

class FileController extends Controller
{
    public function actionCategory($category)
    {
        $model = $this->findCategory($category);

        $ids = [$model->id];

        foreach (Category::findAll(['parent_id' => $model->id]) as $category) {
            $ids[] = $category->id;
        }

        $query = Item::find()->where([
            'category_id' => $ids
        ]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'sort' => [
                // Order by date for default
                'defaultOrder' => [
                    'date' => SORT_DESC,
                ]
            ],
            'pagination' => [
                // Prevent creating additional params in the URL. For SEO
                'forcePageParam' => false,
                'pageSizeParam' => false,
            ],
        ]);

        return $this->render('category', [
            'model' => $model,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($item)
    {
        $model = $this->findModel($item);

        Yii::$app->counter->plus($model);

        return $this->render('item', [
            'model' => $model,
        ]);
    }

    public function actionDownload($item)
    {
        $model = $this->findModel($item);

        $model->downloads++;
        $model->save();

        $file = Yii::getAlias('@frontend/web/uploads/item/' . $model->id . '/' . $model->filename);

        return Yii::$app->response->sendFile($file, $model->filename);
    }

    public function actionRate($item, $up)
    {
        $model = $this->findModel($item);

        $name = md5($model->name . 'views');

        $session = Yii::$app->session;
        $cookies = Yii::$app->request->cookies;

        if (!$session->has($name) and $cookies->has($name)) {
            $session->set($name, $model->id);
        }

        if (!$cookies->has($name) and $session->has($name)) {
            Yii::$app->response->cookies->add(new Cookie([
                'name' => $name,
                'value' => $model->id,
                'expire' => time() + 31556926,
            ]));
        }

        if ($session->has($name) and $cookies->has($name)) {
            $session->setFlash('danger', 'Ваш голос уже был учтен ранее.');
        } else {
            if ($up === '1') {
                $model->likes++;
            } elseif ($up === '2') {
                $model->dislikes++;
            }

            $session->set($name, $model->id);

            Yii::$app->response->cookies->add(new Cookie([
                'name' => $name,
                'value' => $model->id,
                'expire' => time() + 31556926,
            ]));

            $model->save();

            $session->setFlash('success', 'Ваш голос был засчитан');
        }

        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * Finds the Item model based on its slug.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $slug
     * @return Item the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($slug)
    {
        if (($model = Item::findOne(['slug' => $slug])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('Файл не найден');
        }
    }

    /**
     * Finds the Category model based on its slug.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $slug
     * @return Category the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findCategory($slug)
    {
        if (($model = Category::findOne(['slug' => $slug])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('Категория не найдена');
        }
    }

}

backend/views/category/_form.php
<?php

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Category */
/* @var $form yii\widgets\ActiveForm */

$categories = $model->find()->where(['parent_id' => NULL])->all();
$categories = ArrayHelper::map($categories, 'id', 'name');
?>

<div class="category-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'parent_id')->dropDownList($categories, [
        'prompt' => Yii::t('yii', '(not set)'),
    ]) ?>

    <?= $form->field($model, 'slug')
        ->textInput(['maxlength' => 255])
        ->hint('Если пусто - будет сгенерировано с имени') ?>

    <?= $form->field($model, 'meta_description')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'meta_keywords')->textInput(['maxlength' => 255]) ?>

    <div class="form-group">
        <?= Html::submitButton(
            $model->isNewRecord ? 'Добавить' : 'Сохранить',
            ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']
        ) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/category/_search.php
<?php

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\CategorySearch */
/* @var $form yii\widgets\ActiveForm */

$categories = $model->find()->all();
$categories = ArrayHelper::map($categories, 'id', 'name');
?>

<div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
        <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                Поиск категорий
            </a>
        </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
        <div class="panel-body">
            <div class="category-search">

                <?php $form = ActiveForm::begin([
                    'action' => ['index'],
                    'method' => 'get',
                ]); ?>

                <?= $form->field($model, 'id') ?>

                <?= $form->field($model, 'name') ?>

                <?= $form->field($model, 'parent_id')->dropDownList($categories, [
                    'prompt' => '--- Выберите категорию ---',
                ]) ?>

                <?= $form->field($model, 'slug') ?>

                <div class="form-group">
                    <?= Html::submitButton('Поиск', ['class' => 'btn btn-primary']) ?>
                    <?= Html::resetButton('Очистить', ['class' => 'btn btn-default']) ?>
                </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>
    </div>
</div>

backend/views/category/create.php
<?php
/* @var $this yii\web\View */
/* @var $model common\models\Category */

$this->title = 'Добавить Категорию';
$this->params['breadcrumbs'][] = ['label' => 'Категории', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="category-create">

    <h1 class="page-header"><?= $this->title ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/category/index.php
<?php

use kartik\icons\Icon;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\CategorySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Категории';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="category-index">

    <h1 class="page-header">
        <?= $this->title ?>
        <?= Html::a(Icon::show('plus'), ['create'], ['class' => 'btn btn-success pull-right']) ?>
    </h1>

    <?= $this->render('_search', [
        'model' => $searchModel
    ]) ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'summaryOptions' => ['class' => 'alert alert-info'],
        'columns' => [
            'id',
            'name',
            [
                'attribute' => 'parent_id',
                'format' => 'html',
                'value' => function ($model) {
                    return $model->parent ? Html::a($model->parent->name, ['category/view', 'id' => $model->parent->id]) : null;
                },
            ],
            'slug',

            ['class' => 'common\components\ActionButtonGroupColumn'],
        ],
    ]); ?>

</div>

backend/views/category/update.php
<?php
/* @var $this yii\web\View */
/* @var $model common\models\Category */

$this->title = 'Редактировать Категорию: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Категории', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактировать';
?>
<div class="category-update">

    <h1 class="page-header"><?= $this->title ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/category/view.php
<?php

use kartik\icons\Icon;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Category */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Категории', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="category-view">

    <h1 class="page-header">
        <?= $this->title ?>
        <div class="btn-group pull-right">
            <?= Html::a(
                Icon::show('eye'),
                Yii::$app->urlManagerFrontEnd->createUrl(['file/category', 'category' => $model->slug]),
                [
                    'class' => 'btn btn-success',
                    'target' => '_blank',
                    'title' => 'На сайте',
                ]
            ) ?>
            <?= Html::a(
                Icon::show('pencil'),
                ['update', 'id' => $model->id],
                [
                    'class' => 'btn btn-primary',
                    'title' => 'Редактировать',
                ]
            ) ?>
            <?= Html::a(
                Icon::show('trash'),
                ['delete', 'id' => $model->id],
                [
                    'class' => 'btn btn-danger',
                    'title' => 'Удалить',
                    'data' => [
                        'confirm' => 'Вы действительно хотите удалить эту категорию?',
                        'method' => 'post',
                    ]
                ]
            ) ?>
        </div>
    </h1>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            [
                'attribute' => 'parent_id',
                'format' => 'html',
                'value' => $model->parent ? Html::a($model->parent->name, ['category/view', 'id' => $model->parent->id]) : null,
            ],
            'slug',
            'name',
            'meta_description',
            'meta_keywords',
        ],
    ]) ?>

</div>